site_name: Storebrowse Classic Password Insertion for Citrix Receiver for Linux 13.10
site_description: Storebrowse Classic Password Insertion for Citrix Receiver for Linux 13.10
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True
pages:

- Home: index.md
